# Generated by Django 4.2.2 on 2023-06-21 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='added_to_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
