# Generated by Django 4.2.2 on 2023-06-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.FloatField(verbose_name='Bid amount'),
        ),
    ]
